# Generated by Django 4.2.2 on 2024-11-21 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
        migrations.RemoveField(
            model_name="blog",
            name="number_of_views",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="preview",
        ),
        migrations.AddField(
            model_name="blog",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Просмотры"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="blog/image",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора внесения",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="контент статьи"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок",
                max_length=200,
                verbose_name="Заголовок статьи",
            ),
        ),
    ]
