# Generated by Django 5.1.2 on 2024-11-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_client_owner_mailing_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="owner",
        ),
    ]
