# Generated by Django 4.2.2 on 2024-11-10 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0004_start_client_owner_mailing_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempt",
            name="mailing",
        ),
        migrations.DeleteModel(
            name="Contacts",
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="time_end",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="time_sending",
        ),
        migrations.AddField(
            model_name="mailing",
            name="at_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания отправки"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="at_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время начала отправки"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name=""),
        ),
        migrations.AddField(
            model_name="mailing",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mailing/preview",
                verbose_name="Превью",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название рассылки"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                default=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                blank=True, to="messaging.client", verbose_name="Список клиентов"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("C", "Custom"),
                    ("D", "Ежедневно"),
                    ("W", "Еженедельно"),
                    ("M", "Ежемесячно"),
                ],
                max_length=1,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("C", "Создана"), ("R", "Запущена"), ("F", "Завершена")],
                default="C",
                max_length=1,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.DeleteModel(
            name="Attempt",
        ),
    ]
