# Generated by Django 4.2.2 on 2024-11-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_remove_attempt_mailing_delete_contacts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at_last_attempt",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Дата последней попытки",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Успешно"), (2, "Неудачно")],
                        null=True,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="messaging.mailing",
                        verbose_name="попытки",
                    ),
                ),
            ],
            options={
                "ordering": ["-at_last_attempt"],
            },
        ),
    ]
