# Generated by Django 4.2.2 on 2024-11-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_attempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
