# Generated by Django 4.2.2 on 2024-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_alter_message_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[("D", "Ежедневно"), ("W", "Еженедельно"), ("M", "Ежемесячно")],
                max_length=1,
                verbose_name="Периодичность",
            ),
        ),
    ]
